---
title: "LFIAL2260 - Statistics for Linguistics"
author: "Jeroen Claes | <jeroen.claes@kuleuven.be> | <jeroen@cropland.be>"
output:
  html_document:
    theme: lumen
---

Welcome to the companion site for the course *LFIAL2260 - Statistics for linguistics*. All materials on this website are released under the terms of the [CC BY-NC-SA 4.0 license](https://creativecommons.org/licenses/by-nc-sa/4.0/). 

## Slides
The slides for the classes are available for download here: 

- [Topic 1: Introduction: Statistics for linguistics, R, Rstudio, and using R as a calculator](https://drive.google.com/open?id=13ecOT0AIx1YIvqNfzoehtYxrnkund8HjacHGWBb-_tQ)
- [Topic 2: Distributions and basic descriptive statistics for quantitative variables](http://www.jeroenclaes.be/statistics_for_linguistics/slides/Class2.html)
- [Topic 3: Exploring qualitative variables](http://www.jeroenclaes.be/statistics_for_linguistics/slides/Class3.html)
- [Topic 4: Comparing the central tendency of two groups](http://www.jeroenclaes.be/statistics_for_linguistics/slides/Class4.html)
- [Topic 5: Correlations](http://www.jeroenclaes.be/statistics_for_linguistics/slides/Class5.html)
- [Topic 6: Associations between qualitative variables](http://www.jeroenclaes.be/statistics_for_linguistics/slides/Class6.html)
- [Topic 7: Linear regression: Theory and assumptions](http://www.jeroenclaes.be/statistics_for_linguistics/slides/Class7.html)
- [Topic 8: The science (or art?) of fitting linear regression models](http://www.jeroenclaes.be/statistics_for_linguistics/slides/Class8.html)
- [Topic 9: Analysis of Variance](http://www.jeroenclaes.be/statistics_for_linguistics/slides/Class9.html)
- [Topic 10: Logistic regression](http://www.jeroenclaes.be/statistics_for_linguistics/slides/Class10.html)
- [Topic 11: Mixed-effects regression](http://www.jeroenclaes.be/statistics_for_linguistics/slides/Class11.html) 
- [Topic 12: When things aren't quite linear: Polynomial regression and elements of Generalized Additive Modeling](http://www.jeroenclaes.be/statistics_for_linguistics/slides/Class12.html) 

## Syllabus
A version of the slides rendered as Word documents can be found here so can you take notes more easily:

- [Topic 2: Distributions and basic descriptive statistics for quantitative variables](http://www.jeroenclaes.be/statistics_for_linguistics/syllabus/Class2.docx)
- [Topic 3: Exploring qualitative variables](http://www.jeroenclaes.be/statistics_for_linguistics/syllabus/Class3.docx)
- [Topic 4: Comparing the central tendency of two groups](http://www.jeroenclaes.be/statistics_for_linguistics/syllabus/Class4.docx)
- [Topic 5: Correlations](http://www.jeroenclaes.be/statistics_for_linguistics/syllabus/Class5.docx)
- [Topic 6: Associations between qualitative variables](http://www.jeroenclaes.be/statistics_for_linguistics/syllabus/Class6.docx)
- [Topic 7: Linear regression: Theory and assumptions](http://www.jeroenclaes.be/statistics_for_linguistics/syllabus/Class7.docx)
- [Topic 8: The science (or art?) of fitting linear regression models](http://www.jeroenclaes.be/statistics_for_linguistics/syllabus/Class8.docx)
- [Topic 9: Analysis of Variance](http://www.jeroenclaes.be/statistics_for_linguistics/syllabus/Class9.docx)
- [Topic 10: Logistic regression](http://www.jeroenclaes.be/statistics_for_linguistics/syllabus/Class10.docx)
- [Topic 11: Mixed-effects regression](http://www.jeroenclaes.be/statistics_for_linguistics/syllabus/Class11.docx)
- [Topic 12: When things aren't quite linear: Polynomial regression and elements of Generalized Additive Modeling](http://www.jeroenclaes.be/statistics_for_linguistics/syllabus/Class12.docx) 

## Labs
- [Lab 1: Objects, vectors, and basic mathematics](http://www.jeroenclaes.be/statistics_for_linguistics/class1.html)
- [Lab 2: Data frames, measures of central tendency, measures of dispersion, and distributions](http://www.jeroenclaes.be/statistics_for_linguistics/class2.html)
- [Lab 3: Data frames (recap), normal distribution and outliers (recap), and exploring qualitative variables](http://www.jeroenclaes.be/statistics_for_linguistics/class3.html)
- [Lab 4: Comparing the central tendency of two groups](http://www.jeroenclaes.be/statistics_for_linguistics/class4.html)
- [Lab 5: Correlations](http://www.jeroenclaes.be/statistics_for_linguistics/class5.html)
- [Lab 6: Associations between qualitative variables](http://www.jeroenclaes.be/statistics_for_linguistics/class6.html)
- [Lab 7: Linear regression: Theory and assumptions](http://www.jeroenclaes.be/statistics_for_linguistics/class7.html)
- [Lab 8: The science (or art?) of fitting linear regression models](http://www.jeroenclaes.be/statistics_for_linguistics/class8.html)
- [Lab 9: Analysis of Variance](http://www.jeroenclaes.be/statistics_for_linguistics/class9.html)
- [Lab 10: Logistic regression](http://www.jeroenclaes.be/statistics_for_linguistics/class10.html)
- [Lab 11: Mixed-effects regression](http://www.jeroenclaes.be/statistics_for_linguistics/class11.html)
- [Lab 12: When things aren't quite linear: Polynomial regression and elements of Generalized Additive Modeling](http://www.jeroenclaes.be/statistics_for_linguistics/class12.html) 


## R and RStudio cheat sheets (provided by RStudio)
- [Basic R](http://www.jeroenclaes.be/statistics_for_linguistics/cheatsheets/baseR.pdf)
- [RStudio IDE](http://www.jeroenclaes.be/statistics_for_linguistics/cheatsheets/rstudio.pdf)
- [Importing data](http://www.jeroenclaes.be/statistics_for_linguistics/cheatsheets/importingData.pdf)
- [Data visualization with ggplot2 data](http://www.jeroenclaes.be/statistics_for_linguistics/cheatsheets/ggplot2.pdf)

## Recommended literature (available upon request)
- Baayen, R. H. (2008). *Analyzing Linguistic Data: A Practical Introduction to Statistics Using R.* Cambridge: Cambridge University Press.	
- Burnham, K., & Anderson, D. (2002). *Model selection and multi-model inference: A practical information-theoretic approach*. New York, NY: Springer.
- Field, A., Miles, J., & Field, Z. (2012). *Discovering statistics using R*. New York, NY/London: SAGE.
- Fox, J. & Weisberg, S. (2011). *An R companion to applied regression*. Los Angeles, LA: Sage.
- Hosmer, D., Lemeshow, S., & Sturdivant, R. (2013). *Applied logistic regression*. Oxford: Wiley. 
- Gries, S. Th. (2009). *Quantitative corpus linguistics with R.* Berlin/Boston, MA: De Gruyter.	
 - Gries, S. Th. (2013). *Statistics for linguistics with R.* Berlin/Boston, MA: De Gruyter.	
- Harrell, F. E. (2015). *Regression modeling strategies: With applications to linear models, logistic and ordinal Regression, and survival analysis*. New York, NY: Springer.
- Levshina, N. (2015). *How to do linguistics with R.* Amsterdam/Philadelphia, PA: John Benjamins.	
- Urdan, T. C. (2010). *Statistics in plain English.* New York, NY: Routledge.	
- Zuur, A. F., Leno, E. L., Elphick, C. S. (2010). A protocol for data exploration to avoid common statistical problems. *Methods in Ecology and Evolution* 1, 3-14. 
